---
version: '3.9'

services:
  docker-agent-jnlp-node:
    image: ${REPOSITORY:-}linkurious/docker-agent-jnlp-node:${DOCKER_AGENT_JNLP_NODE_VERSION:-0.0.24}
    build:
      context: .
    command: /bin/bash
    tty: true
    stdin_open: true
    # user: ${ID}
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      NPM_TOKEN:
      GH_TOKEN:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:/data
      - ${SSH_AUTH_SOCK}:/ssh-agent
